<?php
/**
 * @var \Amasty\Username\Block\Form $block
 */
?>

<form method="post" action="USERNAME/Username/Username" data-mage-init='{"validation":{"rules": {"sku": {"required":true}}}}'>
    <div>
        <label for="sku">sku:</label>
        <input type="text" name="sku">
    </div>
    <?php if ($block->showQty()): ?>
    <div>
        <label>qty:</label>
        <input type="number" name="qty" value="<?= $block->getQty() ?>" data-validate='{"required":true, "min":1}'>
    </div>
    <?php endif; ?>
    <?= $block->getChildHtml("Amasty_USERNAME.timer")  ?>
    <button type="submit">Отправить</button>
</form>